---
title: "Session-12"
author: "Julia Masterman"
date: "3/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(readr)
library(dplyr)
library(janitor)
library(ggplot2)
```

```{r}
webpage <- read_html("https://www.pwrc.usgs.gov/bbl/manual/speclist.cfm")

tbls <- html_nodes(webpage, "table") %>% 
    html_table(fill = TRUE)

species <- tbls[[1]] %>% 
    clean_names() %>% 
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))
```

Read files into environment
```{r}
pred <- read_csv(url("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9ffec04c-7e2d-41dd-9e88-b6c2e8c4375e"))
nest <- read_csv(url("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A982bd2fc-4edf-4da7-96ef-0d11b853102d"))

#problems(nest)
```

Write a function that will translate species codes into common names
```{r}

code_to_name <- function(dat_code) {
  data_joined <- left_join(dat_code, species, by = c("species" = "alpha_code"))
  return(data_joined)
}

pred_sp_named <- code_to_name(pred)
nest_sp_named <- code_to_name(nest)

##there are ways to reduce the number of variables, fix that funciton and clean this up, see the answers 
```

calculate total number of predators by year and species and plot the result
```{r}
total_pred <- pred_sp_named %>%
  group_by(year,common_name) %>%
  summarize(pred_count = sum(count))

total_pred

ggplot(total_pred, aes(x = year, y = pred_count, fill = common_name)) +
  geom_col()
```

```{r}
total_egg <- nest_sp_named %>%
  group_by(year,common_name) %>%
  summarize(egg_count = sum(number_eggs_predated))

total_egg

ggplot(total_egg, aes(x = year, y = egg_count, fill = common_name)) +
  geom_col()
```

```{r}
total_pred_ann <- total_pred %>%
  group_by(year)%>%
  summarize(pred_count_ann = sum(pred_count))
total_pred_ann

pred_egg_join <- left_join(total_egg, total_pred_ann)
pred_egg_join

#total_egg_ann <- total_egg %>%
 # group_by(year) %>%
  #summarize(egg_count_ann = sum(egg_count))
#total_egg_ann

ggplot(pred_egg_join, aes(x = pred_count_ann, y = egg_count, color = year)) +
  geom_point() +
  facet_wrap(~ common_name) +
  ylab("Predators per Year") +
  xlab("Egg Predation per Year") +
  theme_light()
  



         

```



